version: 2
jobs:
  android:
    working_directory: ~/repo
    docker:
      - image: reactnativecommunity/react-native-android
    steps:
      - checkout
      - run: npm i -g envinfo && envinfo
      - run: yarn install
      # - run: cd android && chmod +x gradlew && ./gradlew assembleRelease
      - run: npm install -g detox-cli react-native-cli
      - run: chmod +x ./test-avd.sh && ./test-avd.sh
      - run: yarn detox build --configuration android.emu.release
      - run: emulator -list-avds
      - run: export QT_DEBUG_PLUGINS=1
      - run: configuration="android.emu.release" yarn detox:cucumber

workflows:
  version: 2
  build_and_test:
    jobs:
      - android
    